"""PDF report generation for FamilyFund.

Generates a 4-page A4 landscape PDF:
  Page 1: Fund Overview (KPIs + NAV trend)
  Page 2: Asset Class Comparison (multi-line chart + donut + table)
  Page 3: P/L Analysis (KPIs + bar chart + table)
  Page 4: Holdings Detail (full table)

Uses matplotlib PdfPages — zero extra dependencies.
"""

import io
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import pandas as pd
from datetime import datetime

matplotlib.rcParams['font.sans-serif'] = [
    'Arial Unicode MS', 'PingFang SC', 'SimHei',       # macOS / Windows
    'Noto Sans CJK JP', 'Noto Sans CJK SC',            # Docker (fonts-noto-cjk)
]
matplotlib.rcParams['axes.unicode_minus'] = False

from nav_engine import CLASS_DISPLAY_NAMES

# ── Style Constants ──

PAGE_SIZE = (11.69, 8.27)  # A4 landscape (inches)
COLORS = ['#2196F3', '#4CAF50', '#FF9800', '#9C27B0', '#F44336', '#00BCD4', '#795548']
COLOR_PROFIT = '#2e7d32'
COLOR_LOSS = '#d32f2f'
TITLE_COLOR = '#1a237e'
HEADER_BG = '#2196F3'
ALT_ROW_BG = '#f5f5f5'
TOTAL_PAGES = 4


# ── Helpers ──

def _add_footer(fig, page_num, report_date):
    fig.text(0.5, 0.02,
             f'Page {page_num} of {TOTAL_PAGES}  \u00b7  Generated by FamilyFund  \u00b7  {report_date}',
             ha='center', fontsize=7, color='#999')


def _render_kpi_row(ax, kpis):
    """Render a row of KPI cards. kpis: list of (label, value) tuples."""
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis('off')
    n = len(kpis)
    for i, (label, value) in enumerate(kpis):
        x = (i + 0.5) / n
        ax.text(x, 0.7, label, fontsize=9, color='#666', ha='center', va='center')
        ax.text(x, 0.3, value, fontsize=15, fontweight='bold', ha='center', va='center',
                color=TITLE_COLOR)


def _render_table(ax, headers, rows, col_widths=None):
    """Render a styled table on the given axes."""
    ax.axis('off')
    if not rows:
        return

    n_cols = len(headers)
    if col_widths is None:
        col_widths = [1.0 / n_cols] * n_cols

    table = ax.table(
        cellText=rows,
        colLabels=headers,
        cellLoc='center',
        loc='center',
        colWidths=col_widths,
    )
    table.auto_set_font_size(False)
    table.set_fontsize(7.5)
    table.scale(1, 1.4)

    # Style header row
    for j in range(n_cols):
        cell = table[0, j]
        cell.set_facecolor(HEADER_BG)
        cell.set_text_props(color='white', fontweight='bold', fontsize=8)
        cell.set_edgecolor('white')

    # Style data rows (alternating)
    for i in range(1, len(rows) + 1):
        for j in range(n_cols):
            cell = table[i, j]
            cell.set_edgecolor('#ddd')
            if i % 2 == 0:
                cell.set_facecolor(ALT_ROW_BG)
            else:
                cell.set_facecolor('white')


# ── Page 1: Fund Overview ──

def _page_overview(pdf, fund_nav_df):
    fig = plt.figure(figsize=PAGE_SIZE, dpi=150)

    latest = fund_nav_df.iloc[-1]
    report_date = latest['Date']
    holdings_note = ''  # will be set by caller if needed

    # Title
    fig.text(0.5, 0.93, 'FamilyFund \u5bb6\u5ead\u57fa\u91d1\u62a5\u544a',
             fontsize=18, fontweight='bold', ha='center', color=TITLE_COLOR)
    fig.text(0.5, 0.89, f'\u62a5\u544a\u65e5\u671f: {report_date}',
             fontsize=10, ha='center', color='#666')

    # KPI row
    ax_kpi = fig.add_axes([0.05, 0.74, 0.9, 0.1])
    _render_kpi_row(ax_kpi, [
        ('\u603b\u8d44\u4ea7', f'\u00a5{latest["Total_Value"]:,.0f}'),
        ('\u5355\u4f4d\u51c0\u503c', f'{latest["NAV"]:.4f}'),
        ('\u7d2f\u8ba1\u6536\u76ca\u7387', f'{latest["Cumulative_Return(%)"]:+.2f}%'),
    ])

    # NAV line chart
    ax_chart = fig.add_axes([0.08, 0.12, 0.84, 0.55])
    dates = pd.to_datetime(fund_nav_df['Date'])
    navs = fund_nav_df['NAV']

    ax_chart.plot(dates, navs, color='#1f77b4', linewidth=2, marker='o', markersize=4)
    ax_chart.axhline(y=1.0, color='red', linestyle='--', linewidth=0.8, alpha=0.5)
    ax_chart.set_title('\u57fa\u91d1\u51c0\u503c\u8d70\u52bf', fontsize=12, fontweight='bold', pad=10)
    ax_chart.set_xlabel('\u65e5\u671f', fontsize=9)
    ax_chart.set_ylabel('\u5355\u4f4d\u51c0\u503c (NAV)', fontsize=9)
    ax_chart.grid(True, linestyle='--', alpha=0.4)
    ax_chart.tick_params(labelsize=8)
    fig.autofmt_xdate(rotation=30)

    _add_footer(fig, 1, report_date)
    pdf.savefig(fig)
    plt.close(fig)


# ── Page 2: Asset Class Comparison ──

def _page_class(pdf, class_nav_dict, allocation_df):
    fig = plt.figure(figsize=PAGE_SIZE, dpi=150)

    fig.text(0.5, 0.93, '\u8d44\u4ea7\u7c7b\u522b\u5bf9\u6bd4',
             fontsize=16, fontweight='bold', ha='center', color=TITLE_COLOR)

    # Left: multi-line NAV chart
    ax_lines = fig.add_axes([0.06, 0.38, 0.42, 0.48])
    for i, (cls, nav_df) in enumerate(sorted(class_nav_dict.items())):
        dates = pd.to_datetime(nav_df['Date'])
        display = CLASS_DISPLAY_NAMES.get(cls, cls)
        color = COLORS[i % len(COLORS)]
        ax_lines.plot(dates, nav_df['NAV'], color=color, linewidth=1.5,
                      marker='o', markersize=3, label=display)

    ax_lines.axhline(y=1.0, color='red', linestyle='--', linewidth=0.7, alpha=0.3)
    ax_lines.set_title('\u5206\u7c7b\u51c0\u503c\u5bf9\u6bd4', fontsize=10, fontweight='bold', pad=8)
    ax_lines.legend(fontsize=6.5, loc='best')
    ax_lines.grid(True, linestyle='--', alpha=0.3)
    ax_lines.tick_params(labelsize=7)
    for label in ax_lines.get_xticklabels():
        label.set_rotation(30)

    # Right: donut pie chart
    ax_pie = fig.add_axes([0.55, 0.38, 0.40, 0.48])
    pie_data = allocation_df[allocation_df['Total_Value'] > 0].sort_values('Total_Value', ascending=False)
    labels = pie_data['Display_Name'].tolist()
    values = pie_data['Total_Value'].tolist()
    pie_colors = COLORS[:len(values)]

    wedges, texts, autotexts = ax_pie.pie(
        values, labels=labels,
        autopct=lambda pct: f'{pct:.1f}%',
        colors=pie_colors, startangle=90, pctdistance=0.78,
        wedgeprops=dict(width=0.4, edgecolor='white', linewidth=1.5),
    )
    for t in texts:
        t.set_fontsize(7)
    for t in autotexts:
        t.set_fontsize(6.5)
    ax_pie.set_title('\u8d44\u4ea7\u914d\u7f6e', fontsize=10, fontweight='bold', pad=8)
    total_val = sum(values)
    ax_pie.text(0, 0, f'\u00a5{total_val:,.0f}', ha='center', va='center',
                fontsize=9, fontweight='bold')

    # Bottom: class performance table
    perf_rows = []
    for _, alloc_row in allocation_df.iterrows():
        cls = alloc_row['Asset_Class']
        display = CLASS_DISPLAY_NAMES.get(cls, cls)
        if cls in class_nav_dict:
            cls_latest = class_nav_dict[cls].iloc[-1]
            nav = f'{cls_latest["NAV"]:.4f}'
            ret = f'{cls_latest["Cumulative_Return(%)"]:+.2f}%'
        else:
            nav = '1.0000'
            ret = '0.00%'
        tv = f'\u00a5{alloc_row["Total_Value"]:,.0f}'
        alloc_pct = f'{alloc_row["Allocation_Percent"] * 100:.1f}%'
        perf_rows.append([display, nav, ret, tv, alloc_pct])

    ax_table = fig.add_axes([0.08, 0.05, 0.84, 0.28])
    _render_table(ax_table,
                  ['\u8d44\u4ea7\u7c7b\u522b', '\u51c0\u503c', '\u6536\u76ca\u7387', '\u5e02\u503c', '\u5360\u6bd4'],
                  perf_rows,
                  col_widths=[0.3, 0.15, 0.15, 0.25, 0.15])

    report_date = allocation_df['Date'].iloc[0] if 'Date' in allocation_df.columns else ''
    _add_footer(fig, 2, report_date)
    pdf.savefig(fig)
    plt.close(fig)


# ── Page 3: P/L Analysis ──

def _page_pnl(pdf, cost_basis_df):
    fig = plt.figure(figsize=PAGE_SIZE, dpi=150)

    fig.text(0.5, 0.93, '\u76c8\u4e8f\u5206\u6790',
             fontsize=16, fontweight='bold', ha='center', color=TITLE_COLOR)

    # KPI row
    total_cost = cost_basis_df['Cost_Basis'].sum()
    total_market = cost_basis_df['Market_Value'].sum()
    total_pl = total_market - total_cost
    total_pl_rate = (total_pl / total_cost * 100) if total_cost > 0 else 0

    ax_kpi = fig.add_axes([0.05, 0.82, 0.9, 0.08])
    _render_kpi_row(ax_kpi, [
        ('\u603b\u6210\u672c', f'\u00a5{total_cost:,.0f}'),
        ('\u603b\u5e02\u503c', f'\u00a5{total_market:,.0f}'),
        ('\u603b\u76c8\u4e8f', f'\u00a5{total_pl:+,.0f}'),
        ('\u603b\u6536\u76ca\u7387', f'{total_pl_rate:+.2f}%'),
    ])

    # Horizontal bar chart
    chart_data = cost_basis_df.sort_values('Profit_Loss', ascending=True).copy()
    bar_colors = [COLOR_PROFIT if v >= 0 else COLOR_LOSS for v in chart_data['Profit_Loss']]
    names = chart_data['Name'].tolist()

    n_bars = len(names)
    chart_height = min(0.42, max(0.2, n_bars * 0.025))
    ax_bar = fig.add_axes([0.12, 0.78 - chart_height, 0.80, chart_height])
    ax_bar.barh(range(n_bars), chart_data['Profit_Loss'], color=bar_colors, height=0.6)
    ax_bar.set_yticks(range(n_bars))
    ax_bar.set_yticklabels(names, fontsize=7)
    ax_bar.set_xlabel('\u76c8\u4e8f (CNY)', fontsize=8)
    ax_bar.set_title('\u6301\u4ed3\u76c8\u4e8f', fontsize=10, fontweight='bold', pad=8)
    ax_bar.axvline(x=0, color='#333', linewidth=0.5)
    ax_bar.grid(True, axis='x', linestyle='--', alpha=0.3)
    ax_bar.tick_params(labelsize=7)

    # P/L detail table
    table_rows = []
    for _, row in cost_basis_df.iterrows():
        pl_rate = f'{row["Profit_Loss_Rate"]:.2f}%' if pd.notna(row.get('Profit_Loss_Rate')) else '-'
        table_rows.append([
            row['Name'],
            f'\u00a5{row["Cost_Basis"]:,.0f}',
            f'\u00a5{row["Market_Value"]:,.0f}',
            f'\u00a5{row["Profit_Loss"]:+,.0f}',
            pl_rate,
        ])

    table_top = 0.78 - chart_height - 0.04
    table_height = max(0.05, table_top - 0.06)
    ax_table = fig.add_axes([0.08, 0.06, 0.84, table_height])
    _render_table(ax_table,
                  ['\u540d\u79f0', '\u6210\u672c', '\u5e02\u503c', '\u76c8\u4e8f', '\u6536\u76ca\u7387'],
                  table_rows,
                  col_widths=[0.3, 0.2, 0.2, 0.2, 0.1])

    _add_footer(fig, 3, '')
    pdf.savefig(fig)
    plt.close(fig)


# ── Page 4: Holdings Detail ──

def _page_holdings(pdf, df):
    latest_date = df['Date'].max()
    holdings = df[df['Date'] == latest_date].copy()
    holdings = holdings.sort_values('Total_Value', ascending=False)

    fig = plt.figure(figsize=PAGE_SIZE, dpi=150)
    fig.text(0.5, 0.93, f'\u6301\u4ed3\u660e\u7ec6  ({latest_date})',
             fontsize=16, fontweight='bold', ha='center', color=TITLE_COLOR)

    rows = []
    for _, row in holdings.iterrows():
        display_class = CLASS_DISPLAY_NAMES.get(row['Asset_Class'], row['Asset_Class'])
        rows.append([
            display_class,
            row['Platform'],
            row['Name'],
            str(row.get('Code', '')),
            f'{row["Shares"]:,.2f}',
            f'{row["Current_Price"]:.4f}',
            f'\u00a5{row["Total_Value"]:,.2f}',
        ])

    ax_table = fig.add_axes([0.04, 0.06, 0.92, 0.82])
    _render_table(ax_table,
                  ['\u8d44\u4ea7\u7c7b\u522b', '\u5e73\u53f0', '\u540d\u79f0', '\u4ee3\u7801',
                   '\u4efd\u989d', '\u5f53\u524d\u4ef7\u683c', '\u603b\u5e02\u503c'],
                  rows,
                  col_widths=[0.15, 0.12, 0.15, 0.1, 0.15, 0.15, 0.18])

    _add_footer(fig, 4, latest_date)
    pdf.savefig(fig)
    plt.close(fig)


# ── Main Entry Point ──

def generate_report(df, fund_nav_df, class_nav_dict, allocation_df, cost_basis_df):
    """Generate a PDF report for the family fund.

    Args:
        df: Raw portfolio DataFrame
        fund_nav_df: Fund-level NAV DataFrame
        class_nav_dict: {Asset_Class: NAV DataFrame}
        allocation_df: Asset allocation DataFrame
        cost_basis_df: Cost basis / P&L DataFrame

    Returns:
        bytes: PDF file content (for st.download_button)
    """
    buf = io.BytesIO()
    with PdfPages(buf) as pdf_file:
        _page_overview(pdf_file, fund_nav_df)
        _page_class(pdf_file, class_nav_dict, allocation_df)
        _page_pnl(pdf_file, cost_basis_df)
        _page_holdings(pdf_file, df)
    buf.seek(0)
    return buf.getvalue()
